/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encrypta3;

/**
 *
 * @author yo
 */
public class Encrita3_GUI extends javax.swing.JFrame {

    private MensajesJPanel mensJP;
    private CambiarClavesJPanel cClavesJP;
    public Encrita3_GUI() {
        initComponents();
        
        mensJP=new MensajesJPanel();
        add(mensJP);
        mensJP.setVisible(false);
        cClavesJP=new CambiarClavesJPanel();
        add(cClavesJP);
        cClavesJP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        ArchivoMBar = new javax.swing.JMenu();
        SalirOp = new javax.swing.JMenuItem();
        opcionMBar = new javax.swing.JMenu();
        MensajesOp = new javax.swing.JMenuItem();
        CClavesOp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(5, 5));
        setPreferredSize(new java.awt.Dimension(680, 590));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        ArchivoMBar.setText("Archivo");

        SalirOp.setText("Salir");
        ArchivoMBar.add(SalirOp);

        jMenuBar1.add(ArchivoMBar);

        opcionMBar.setText("Opcion");

        MensajesOp.setText("MensajesPanel");
        MensajesOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionActionPerformed(evt);
            }
        });
        opcionMBar.add(MensajesOp);

        CClavesOp.setText("CambiarClavesPanel");
        CClavesOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionActionPerformed(evt);
            }
        });
        opcionMBar.add(CClavesOp);

        jMenuBar1.add(opcionMBar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionActionPerformed
        ocultarPaneles();
        switch (evt.getActionCommand()) {
            case "MensajesPanel": 
                ocultarPaneles();
                mensJP.mostrar();
                break;
            case "CambiarClavesPanel": 
                ocultarPaneles();
                cClavesJP.mostrar();
                break;
        }
    }//GEN-LAST:event_OpcionActionPerformed
    
    public void ocultarPaneles(){
        mensJP.setVisible(false);
        cClavesJP.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encrita3_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encrita3_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encrita3_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encrita3_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encrita3_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArchivoMBar;
    private javax.swing.JMenuItem CClavesOp;
    private javax.swing.JMenuItem MensajesOp;
    private javax.swing.JMenuItem SalirOp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu opcionMBar;
    // End of variables declaration//GEN-END:variables
}
